services:
  nginx:
    build:
      context: ./nginx-cfg
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - frontend
  frontend:
    build:
      context: ./gpt-direct-front
      dockerfile: Dockerfile
