services:
  nginx:
    build:
      context: ./nginx-cfg
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - frontend
      - backend
  frontend:
    build:
      context: ./gpt-direct-front
      dockerfile: Dockerfile
      args:
        API_URL: testspring.hydris.dev/api
  backend:
    build:
      context: ./gpt-direct-back
      dockerfile: Dockerfile

