services:
  nginx:
    build:
      context: ./nginx-cfg
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - frontend
  frontend:
    build:
      environment:
        API_URL: testspring.hydris.dev/app
      context: ./gpt-direct-front
      dockerfile: Dockerfile
