services:
  nginx:
    build:
      context: ./nginx-cfg
      dockerfile: Dockerfile
    ports:
      - "4000:80"
    depends_on:
      - frontend
      - backend
  frontend:
    build:
      context: ./gpt-direct-front
      dockerfile: Dockerfile
  backend:
    build:
      context: ./gpt-direct-back
      dockerfile: Dockerfile
    secrets:
      - openai_key
      - login_key
secrets:
  openai_key:
    file: ./openai_key.txt
  login_key:
    file: ./login_key.txt
